In [15]:
import torch
import numpy as np

In [16]:
data = [[1,2,3],[2,4,6]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2, 3],
        [2, 4, 6]])

In [17]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2, 3],
        [2, 4, 6]])

In [19]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n {x_ones}\n")

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]])



In [21]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Ones Tensor: \n{x_rand} \n")

Ones Tensor: 
tensor([[0.8384, 0.1146, 0.8500],
        [0.3847, 0.6770, 0.0454]]) 



In [ ]:
shape = (3,3,)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.2942, 0.8967, 0.9998],
        [0.3568, 0.9725, 0.8912],
        [0.2546, 0.8199, 0.2815]])

In [24]:
one_tenser = torch.ones(shape)
one_tenser

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

<h3>Attributes of a tensor</h3>

In [28]:
tensor = torch.rand(3,4)
print(f"shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [34]:
tensor = torch.rand(3,4)
print(f"First row: {tensor[0]}")
print(f"First Column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
print(f"Last row: {tensor[-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.2126, 0.9771, 0.0319, 0.4134])
First Column: tensor([0.2126, 0.1064, 0.8848])
Last column: tensor([0.4134, 0.4345, 0.1566])
Last row: tensor([0.8848, 0.9231, 0.0638, 0.1566])
tensor([[0.2126, 0.0000, 0.0319, 0.4134],
        [0.1064, 0.0000, 0.7954, 0.4345],
        [0.8848, 0.0000, 0.0638, 0.1566]])


In [36]:
tensor2 = torch.cat([tensor,tensor],dim=1)
print(tensor2)

tensor([[0.2126, 0.0000, 0.0319, 0.4134, 0.2126, 0.0000, 0.0319, 0.4134],
        [0.1064, 0.0000, 0.7954, 0.4345, 0.1064, 0.0000, 0.7954, 0.4345],
        [0.8848, 0.0000, 0.0638, 0.1566, 0.8848, 0.0000, 0.0638, 0.1566]])


In [38]:
y1 = tensor @ tensor.T
y1

tensor([[0.2171, 0.2276, 0.2549],
        [0.2276, 0.8328, 0.2129],
        [0.2549, 0.2129, 0.8115]])

In [39]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[0.2171, 0.2276, 0.2549],
        [0.2276, 0.8328, 0.2129],
        [0.2549, 0.2129, 0.8115]])

In [40]:
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[0.2171, 0.2276, 0.2549],
        [0.2276, 0.8328, 0.2129],
        [0.2549, 0.2129, 0.8115]])

In [41]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)


In [42]:
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[0.0452, 0.0000, 0.0010, 0.1709],
        [0.0113, 0.0000, 0.6327, 0.1888],
        [0.7829, 0.0000, 0.0041, 0.0245]])