> creating tensor

In [1]:
pip install tensorflow==2.20.0

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf

In [22]:
# creating tensor using constant
scalar = tf.constant(14)
vector = tf.constant([1,2,3,4],dtype=tf.int32)
matrix = tf.constant([[1,2,3],[4,5,6]])

# creating tensor using variable
variable = tf.Variable([1.0,2.0,3.0],[10.0,9.0,8.0])

# creating tensor with random value
random_tensor = tf.random.uniform(shape=(2,4),minval=0,maxval=10,dtype = tf.int32)

In [14]:
print(random_tensor)

tf.Tensor(
[[8 2 0 2]
 [8 2 7 4]], shape=(2, 4), dtype=int32)


In [21]:
print(matrix)
print('\nmatrix:',matrix)
print('\n data type:',matrix.dtype)
print('\n Rank:',tf.rank(matrix).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

matrix: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

 data type: <dtype: 'int32'>

 Rank: 2


* shape
    * rank {0,1,2,...}
    * dimension{1D: scaler, 2D: vector, 3D:matrix}

### batch of data
<pre>
for 3D of higher
    * Images: (batch_size, height, width, channels)
    Example: (32, 224, 224, 3) for a batch of 32 RGB images.
    * Sequences: (batch_size, time_steps, features)
    Example: (64, 100, 50) for a batch of 64 sequences, each with 100 time steps and 50 features.
</pre>


## tensor manipulation
* reshape
* expand_dims
* squeeze
* transpose

In [24]:
# casting data type in tensor
casted_tensor = tf.cast(vector,dtype=tf.float32)
print(casted_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [33]:
import tensorflow as tf

# Creating a 3-D tensor (batch of 2 images, 3x3 pixels, 1 channel)
tensor = tf.constant([
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]],
    
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]]
], dtype=tf.uint8)

print("Tensor:\n", tensor)
print("Shape:", tensor.shape)
print("Data Type:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# # Reshaping the tensor to flatten the images
reshaped_tensor = tf.reshape(tensor, (2, 9))
print("Reshaped Tensor:\n", reshaped_tensor)
print("New Shape:", reshaped_tensor.shape)

Tensor:
 tf.Tensor(
[[[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]


 [[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]], shape=(2, 3, 3, 1), dtype=uint8)
Shape: (2, 3, 3, 1)
Data Type: <dtype: 'uint8'>
Rank: 4
Reshaped Tensor:
 tf.Tensor(
[[255   0 127 255   0 127 255   0 127]
 [255   0 127 255   0 127 255   0 127]], shape=(2, 9), dtype=uint8)
New Shape: (2, 9)


# Basic tensor operations

> ### arithmetic operation

In [43]:
# addition
a = tf.constant([1,2,6,5])
b = tf.constant([4,5,6,8])
c = tf.add(a,b)
print(f"addition:",c)


# subtraction
print("subtract:",tf.subtract(a,b))

#multi
print("multiplication:",tf.multiply(a,b))

# division
print("division",tf.divide(a,b))

addition: tf.Tensor([ 5  7 12 13], shape=(4,), dtype=int32)
subtract: tf.Tensor([-3 -3  0 -3], shape=(4,), dtype=int32)
multiplication: tf.Tensor([ 4 10 36 40], shape=(4,), dtype=int32)
division tf.Tensor([0.25  0.4   1.    0.625], shape=(4,), dtype=float64)


> ### matrix operations

In [50]:
matrix1 = matrix
matrix2 = tf.constant([[3,4],[7,3],[3,4]])
print(matrix.shape,matrix2.shape)

(2, 3) (3, 2)


In [ ]:
# matrix multiplication
print(tf.matmul(matrix1,matrix2))

tf.Tensor(
[[26 22]
 [65 55]], shape=(2, 2), dtype=int32)


In [52]:
# transpose operation
print(tf.transpose(matrix1))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
