In [2]:
import numpy as np

In [3]:
arr_list = np.array([2,3,5,3])
arr_tup = np.array((2,3,4,5,3))

In [4]:
print(arr_list , arr_tup)
print(type(arr_list))
print(type(arr_tup))

[2 3 5 3] [2 3 4 5 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


> array dimentions

In [5]:
arr_zero = np.array(14)
arr_one = np.array([14,30,9,5])
arr_two = np.array([[2,4,6],[1,3,5]])
arr_three = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

In [6]:
print(arr_zero.ndim)
print(arr_one.ndim)
print(arr_two.ndim)
print(arr_three.ndim)


0
1
2
3


In [7]:
print(arr_three)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


> multi dimention array

In [8]:
arr_multi = np.array([1,2,3,4,5],ndmin=5)
print(arr_multi)
print(arr_multi.ndim)

[[[[[1 2 3 4 5]]]]]
5


## Access Array Elements

In [9]:
print(arr_one)
print(arr_one[3])
print(arr_one[0]+arr_one[1])

[14 30  9  5]
5
44


> accessing 2D array

In [10]:
print(arr_two)
print("element at 2nd row and 3rd column is : ",arr_two[1,2])

[[2 4 6]
 [1 3 5]]
element at 2nd row and 3rd column is :  5


In [11]:
print(arr_two[-2,-1])

6


> accessing 3D array

In [12]:
print(arr_three)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [13]:
print(" 1st element of 2nd array's 2nd array is : ",arr_three[1,1,0])

 1st element of 2nd array's 2nd array is :  40


## array slicing


> 1D array

In [14]:
print(arr_one)
print(arr_one[2:5])
print(arr_one[-4:-1])

[14 30  9  5]
[9 5]
[14 30  9]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[::2])

[1 3 5 7 9]


> 2D array

In [16]:
print(arr_two)

[[2 4 6]
 [1 3 5]]


In [17]:
print(arr_two[1,0:])
print(arr_two[1,0:2])


[1 3 5]
[1 3]


In [18]:
# from both element return 3rd element
print(arr_two[0:2,2])

[6 5]


In [19]:
print(arr_two[0:,0:2])

[[2 4]
 [1 3]]


## data types

<pre>Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
</pre>

In [20]:
arr_int = arr_one
arr_str = np.array(["ram","shayam","hari","vidya","siya"])

In [21]:
print(arr_str.dtype)
print(arr_int.dtype)

<U6
int64


In [22]:
arr_intstr = np.array([1,2,3,4,5],dtype='S')
print(arr_intstr.dtype)

|S1


For i, u, f, S and U we can define size as well.

In [23]:
# create a datatype for 4bit integer
arr_newint = np.array([1,2,3,4],dtype='i4')

converting data type of existing array, best way is to make a copy of the array with the "astype()"

In [24]:
arr_float = np.array([1.1, 2.1, 3.1])
floatarr = arr_float.astype('i')
# floatarr = arr_float.astype(int)  # int can be done using int as an argument
print(arr_float)
print(floatarr)
print(floatarr.dtype)


[1.1 2.1 3.1]
[1 2 3]
int32


In [25]:
print(np.array([1,0,3,5]).astype(bool))

[ True False  True  True]


# Array copy vs View


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

> copy

In [38]:
x = arr_one.copy()
arr_one[2] = 9

print(arr_one)
print(x)

[14 30  9  5]
[14 30 10  5]


> view

In [42]:
y = arr_one.view()
arr_one[3] = 5

print(arr_one)
print(y)

[14 30  9  5]
[14 30  9  5]


> Check if Array Owns its Data


As mentioned above, copies `owns` the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute `base` that returns `None` if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [44]:
print(x.base)
print(y.base)

None
[14 30  9  5]


# numPy array shape

In [46]:
print(arr_one.shape)
print(arr_two.shape)

(4,)
(2, 3)


In [48]:
test_arr = np.array([1,2,4,5,3,3],ndmin=5)
print(test_arr.shape)

(1, 1, 1, 1, 6)


# Array Reshaping

>1D to 2D

In [50]:
newarr = arr_one.reshape(2,2)
print(newarr)

[[14 30]
 [ 9  5]]


> 1D to 3D

In [53]:
newarr1 = arr_one.reshape(1,1,4)
print(newarr1)
newarr1.base

[[[14 30  9  5]]]


array([14, 30,  9,  5])

> Unknownn dimension

we can create one `unknown` dimension by pass -1 as the value to one of the dimensions in the reshape method

In [65]:
newarr = arr_one.reshape(2,2,-1)
print(newarr)



[[[14]
  [30]]

 [[ 9]
  [ 5]]]


we can't pass -1 to more than one dimension

> Flattening the array

converting array into 1D

In [66]:
arr_three.reshape(-1)

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

# NumPy Array Iteration

>1D array

In [67]:
for _ in arr_one:
    print(_)

14
30
9
5


If we iterate on a n-D array it will go through n-1th dimension one by one.

>2D array

In [74]:
for _ in arr_two:
    print(_)

[2 4 6]
[1 3 5]


<p> iterating each scaler element of 2D array</p>

In [73]:
print(arr_two)
for i in arr_two:
    for j in i:
        print(j)

[[2 4 6]
 [1 3 5]]
2
4
6
1
3
5


> 3D array

In [75]:
for _ in arr_three:
    print(_)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


<p> to return the actual value</p>

In [76]:
for x in arr_three:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
10
20
30
40
50
60


>> Iterating Array using `nditer()`

> 3D array iteration

In [77]:
for x in np.nditer(arr_three):
    print(x)

1
2
3
4
5
6
10
20
30
40
50
60


> Iterating Array with Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass flags=`['buffered']`.

In [83]:
for x in np.nditer(arr_one,flags=['buffered'],op_dtypes=['S']):
    print(x)

np.bytes_(b'14')
np.bytes_(b'30')
np.bytes_(b'9')
np.bytes_(b'5')


> Iterating With Different Step Size


Iterate through every scalar element of the 2D array skipping 1 element:

In [86]:
# Iterate through every scalar element of the 2D array skipping 1 element:

arrNew = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arrNew[:, ::2]):
    print(x)

1
3
5
7


# NumPy Joining Array

* putting contents of two or more than two array into single array
* we pass a sequence of arrays that we want to join to the `concatenate()` funct, along with the axis, if axis is not explicitly passed, it taken as 0.

In [89]:
NewArr_one = np.array([12,24,36,48,60])

arrJoin = np.concatenate((arr_one,NewArr_one))
print(arrJoin)


[14 30  9  5 12 24 36 48 60]


> join 2D array

In [93]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


>>Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0.


In [104]:
newarr1 = np.array([1, 2, 3])

newarr2 = np.array([4, 5, 6])

print(np.stack((newarr1,newarr2),axis = 1))

[[1 4]
 [2 5]
 [3 6]]


> stacking along rows

In [105]:
print(np.hstack((newarr1,newarr2)))

[1 2 3 4 5 6]


> stacking along columns

In [106]:
print(np.vstack((newarr1,newarr2)))

[[1 2 3]
 [4 5 6]]


> stacking along Height(depth)

NumPy provides a helper function: `dstack()` to stack along height, which is the same as depth.

In [108]:
print(np.dstack((newarr1,newarr2)))

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array
* it's reverse of joining operation
* splitting breaks one array into multiple.
* using `array_split()` for splitting arrays, we pass it array to split and the number of splits.

In [113]:
new1Darr = np.array([1,2,3,4,5,6])
print(np.array_split(new1Darr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


*  The return value is a list containing three arrays.
* If the array has less elements than required, it will adjust from the end accordingly.

In [114]:
print(np.array_split(new1Darr,4))


[array([1, 2]), array([3, 4]), array([5]), array([6])]


We also have the method `split()` available but it will not adjust the elements when elements are less in source array for splitting like in example above, `array_split()` worked properly but `split()` would fail.

> split into arrays
* return value of `array_split()` method is a list containing each of the split as an array.


In [118]:
narr = np.array([1,2,3,4,5,6])
newnarr = np.array_split(narr,3)
print(newnarr[0])

[1 2]


> Splitting 2D array

In [119]:
print(arr_two)

[[2 4 6]
 [1 3 5]]


In [126]:
print(np.array_split(arr_two,2))

[array([[2, 4, 6]]), array([[1, 3, 5]])]


In [129]:
bigarr_two = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newbigarr_two = np.array_split(bigarr_two,3)
print(newbigarr_two)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


> specifying axis

In [130]:
print(np.array_split(bigarr_two,3,axis=1))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


* an alternate sol<sup>n</sup> is using `hsplit() opposite of `hstack()`

In [131]:
print(np.hsplit(bigarr_two,3))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


 Similar alternates to `vstack()` and `dstack()` are available as `vsplit()` and `dsplit()`

# Numpy Searching Arrays

* we can search an array for a certain value, and return the indexes that get a match. we can do so by using `where()` method.

In [138]:
print(arr_one)
x = np.where(arr_one==30)    # returns all the indexes where the value is present
print(x)    

[14 30  9  5]
(array([1]),)


In [139]:
# return even value
print(np.where(arr_one%2==0))

(array([0, 1]),)


# Search sorted
* `searchsorted()` method performs a binary search in the array, and returns the index where the specific value would be inserted to maintain the search order.
* method is assumed to be used on sorted arrays.

In [ ]:
print(np.searchsorted(np.array([5,9,14,30,1430]),21))

3


* The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

> Search from the right side
* By default the left most index is returned, but we can give `side='right'` to return the right most index instead.

In [145]:
print(np.searchsorted(arr3,10,side='right'))

2


* The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

> Multiple values

In [146]:
print(np.searchsorted(arr3,[2,4,90]))

[0 0 4]


# Numpy Sorted Array
* using ` sort()` function

In [157]:
print(np.sort(np.array([2,42,30,10,4,5,3,13,15321,14,4])))

[    2     3     4     4     5    10    13    14    30    42 15321]


* it returns the `copy` of array

> sorting 2D array

In [158]:
print(np.sort(np.array([[2,7,3,5],[3,854,11,5]])))

[[  2   3   5   7]
 [  3   5  11 854]]


# Array Filtering
* creating new array from existing array by getting some element
* we filter using a boolean index list
* `boolean index` is a list of boolean corresponding to indexes in the array
* If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.


In [166]:
x = [True,False,True,False]
print(arr_one)
print(arr_one[x])

[14 30  9  5]
[14  9]


 the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

> Creating the Filter Array
In the example above we hard-coded the `True` and `False` values, but the common use is to create a filter array based on conditions.

In [168]:
# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr_one:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


print(filter_arr)
print(arr[filter_arr])

[False, False, False, False]
[]


In [170]:
# return even elements
# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr_one:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

print(filter_arr)
print(arr_one[filter_arr])

[True, True, False, False]
[14 30]


> Creating Filter Directly From Array

In [ ]:
# Create a filter array that will return only values higher than 13
filter_arr = arr_one > 13

print(filter_arr)
print(arr_one[filter_arr])

[ True  True False False]
[14 30]
