In [77]:
import numpy as np

In [78]:
arr = np.array([2,3,4,2,1])
print(arr)

[2 3 4 2 1]


In [79]:
print("first element:",arr[0])

first element: 2


In [80]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [81]:
print(arr2[0][0])
print(arr2[1][2])

1
6


## finding dimention of the array

In [82]:
print(arr2.ndim)

2


In [83]:
print(arr.ndim)

1


## negative indexing

In [84]:
print(arr)
print(arr[-1])

[2 3 4 2 1]
1


In [85]:
print(arr2)
print(arr2[-1,-2])

[[1 2 3]
 [4 5 6]]
5


In [86]:
print(arr2[1,-1])

6


## array slicing

In [87]:
print(arr)
print(arr[0:1])
print(arr[0:4:2])

[2 3 4 2 1]
[2]
[2 4]


In [89]:
print(arr2)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## data type of array

In [90]:
print(arr.dtype)

int64


## copy operation on array

In [92]:
print(arr)

[2 3 4 2 1]


In [93]:
X = arr.copy()

In [94]:
arr==X

array([ True,  True,  True,  True,  True])

## iteration of 1D array

In [95]:
for _ in arr:
    print(_)

2
3
4
2
1


## iteration of 2D array

In [96]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [97]:
for _ in arr2:
    print(_)

[1 2 3]
[4 5 6]


## print and display shape of an array

In [98]:
print(arr2.shape)   ## two rows and 3 columns

(2, 3)


## reshaping 1D array to 2D 

In [112]:
new_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [113]:
b = new_arr.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## joining two array

In [114]:
print(arr)
print(new_arr)

[2 3 4 2 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [131]:
arr1 = np.concatenate((arr,new_arr))
print(arr1)

[ 2  3  4  2  1  1  2  3  4  5  6  7  8  9 10 11 12]


## splitting an arrays

In [132]:
arr1 = np.array_split(arr1,1)
arr1

[array([ 2,  3,  4,  2,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]

## sorting array

In [134]:
print(arr1)
print(np.sort(arr1))

[array([ 2,  3,  4,  2,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]
[[ 1  1  2  2  2  3  3  4  4  5  6  7  8  9 10 11 12]]


In [136]:
string_arr = np.array(['cat','bat','vivek'])
print(np.sort(string_arr))

['bat' 'cat' 'vivek']


In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [142]:
new_arr2 = np.array([[2,30,5,23],[5,4,1,14]])
print(new_arr2)
print(np.sort(new_arr2))

[[ 2 30  5 23]
 [ 5  4  1 14]]
[[ 2  5 23 30]
 [ 1  4  5 14]]


## searching in array

In [144]:
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [151]:
search = np.where(new_arr==10)
print(search)

(array([9]),)


In [152]:
even = np.where(new_arr%2==0)
print(even)

(array([ 1,  3,  5,  7,  9, 11]),)


## random number


In [153]:
from numpy import random

In [193]:
x = random.randint(100)
print(x)

92


## generation random array

In [199]:
random_arr = random.randint(100,size=(5))
print(random_arr)

[43 57 45 22 97]
