In [2]:
import numpy as np

In [3]:
arr_list = np.array([2,3,5,3])
arr_tup = np.array((2,3,4,5,3))

In [4]:
print(arr_list , arr_tup)
print(type(arr_list))
print(type(arr_tup))

[2 3 5 3] [2 3 4 5 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


> array dimentions

In [5]:
arr_zero = np.array(14)
arr_one = np.array([14,30,9,5])
arr_two = np.array([[2,4,6],[1,3,5]])
arr_three = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

In [6]:
print(arr_zero.ndim)
print(arr_one.ndim)
print(arr_two.ndim)
print(arr_three.ndim)


0
1
2
3


In [7]:
print(arr_three)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


> multi dimention array

In [8]:
arr_multi = np.array([1,2,3,4,5],ndmin=5)
print(arr_multi)
print(arr_multi.ndim)

[[[[[1 2 3 4 5]]]]]
5


## Access Array Elements

In [9]:
print(arr_one)
print(arr_one[3])
print(arr_one[0]+arr_one[1])

[14 30  9  5]
5
44


> accessing 2D array

In [10]:
print(arr_two)
print("element at 2nd row and 3rd column is : ",arr_two[1,2])

[[2 4 6]
 [1 3 5]]
element at 2nd row and 3rd column is :  5


In [11]:
print(arr_two[-2,-1])

6


> accessing 3D array

In [12]:
print(arr_three)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [13]:
print(" 1st element of 2nd array's 2nd array is : ",arr_three[1,1,0])

 1st element of 2nd array's 2nd array is :  40


## array slicing


> 1D array

In [14]:
print(arr_one)
print(arr_one[2:5])
print(arr_one[-4:-1])

[14 30  9  5]
[9 5]
[14 30  9]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[::2])

[1 3 5 7 9]


> 2D array

In [16]:
print(arr_two)

[[2 4 6]
 [1 3 5]]


In [17]:
print(arr_two[1,0:])
print(arr_two[1,0:2])


[1 3 5]
[1 3]


In [18]:
# from both element return 3rd element
print(arr_two[0:2,2])

[6 5]


In [19]:
print(arr_two[0:,0:2])

[[2 4]
 [1 3]]


## data types

<pre>Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
</pre>

In [ ]:
arr_int = arr_one
arr_str = np.array(["ram","shayam","hari","vidya","siya"])

In [ ]:
print(arr_str.dtype)
print(arr_int.dtype)

<U6
int64


In [22]:
arr_intstr = np.array([1,2,3,4,5],dtype='S')
print(arr_intstr.dtype)

|S1


For i, u, f, S and U we can define size as well.

In [23]:
# create a datatype for 4bit integer
arr_newint = np.array([1,2,3,4],dtype='i4')

converting data type of existing array, best way is to make a copy of the array with the "astype()"

In [24]:
arr_float = np.array([1.1, 2.1, 3.1])
floatarr = arr_float.astype('i')
# floatarr = arr_float.astype(int)  # int can be done using int as an argument
print(arr_float)
print(floatarr)
print(floatarr.dtype)


[1.1 2.1 3.1]
[1 2 3]
int32


In [25]:
print(np.array([1,0,3,5]).astype(bool))

[ True False  True  True]
